/**
 * Fixed replies for questions that should not get a decision screen. Written by people and
 * reviewed like any other guidance wording; never generated by a model.
 */

export type MessageReason = 'about' | 'lookup' | 'not_supported' | 'human' | 'distress' | 'clarify' | 'needs_facts' | 'blocked' | 'failed';

export interface ForkMessage {
  kind: 'message';
  reason: MessageReason;
  title: string;
  body: string;
  /** Who can help next. */
  routeTo: 'documents' | 'owner' | 'accountant' | 'support' | null;
  /** Where a looked-up answer came from, such as "Staff handbook, page 4". */
  source?: string;
  /** For "not yet": the decisions Fork can help with today. */
  canHelpWith?: string[];
  /** For "blocked": the last round of checks, kept with the run so the cause can be found later. */
  checks?: { code: string[]; issues: Array<{ kind: string; sendBackTo: string; detail: string }> };
}

export const DISTRESS: ForkMessage = {
  kind: 'message',
  reason: 'distress',
  title: 'That sounds really hard',
  body:
    'You don’t have to work this out alone. MoneyHelper gives free, impartial help with money worries, paid for by the government: moneyhelper.org.uk. ' +
    'If things feel like too much, Samaritans are there any time on 116 123. ' +
    'If it would help to talk about your pay or pension at work, you can ask your employer privately. Fork won’t tell them you asked.',
  routeTo: 'support',
};

/** An honest "not yet", with what Fork can help with today for this person. */
export const notYet = (titles: string[]): ForkMessage => ({ ...NOT_SUPPORTED, canHelpWith: titles });

export const NOT_SUPPORTED: ForkMessage = {
  kind: 'message',
  reason: 'not_supported',
  title: 'Fork can’t answer that one yet',
  body: 'This is a real decision, but Fork doesn’t have the rules and numbers to work it out reliably yet. Your accountant or employer can help in the meantime.',
  routeTo: 'accountant',
};

export const HUMAN: ForkMessage = {
  kind: 'message',
  reason: 'human',
  title: 'This one needs a person',
  body: 'Fork gives guidance on pay, pensions and benefits at work. For this question, talk to your employer, your accountant or a regulated adviser.',
  routeTo: 'owner',
};

export const LOOKUP_UNKNOWN: ForkMessage = {
  kind: 'message',
  reason: 'lookup',
  title: 'Fork couldn’t find that yet',
  body: 'Fork answers plain questions from your payroll and your company’s confirmed documents, and this isn’t in them yet. Your employer or accountant will know.',
  routeTo: 'owner',
};

/** Nothing found, with what Fork can help with instead, so the person isn't left at a dead end. */
export const lookupUnknown = (titles: string[]): ForkMessage => ({ ...LOOKUP_UNKNOWN, canHelpWith: titles });

/** "What can you do?": what Fork answers, what it uses, and who can see it. */
export const about = (audience: 'employee' | 'owner', titles: string[]): ForkMessage => ({
  kind: 'message',
  reason: 'about',
  title: 'What Fork can help with',
  body:
    audience === 'employee'
      ? 'Fork works out the decisions below with your own numbers. Ask in your own words. ' +
        'You can also ask plain questions, such as your pay, your pension contribution or where your payslips are.\n' +
        'Fork uses your pay, hours and pension details from payroll, your company’s pension scheme and confirmed documents, and this year’s tax rules. ' +
        'Your employer never sees your questions or your answers.'
      : 'Fork works out the decisions below for your company, with your payroll and this year’s tax rules. Ask in your own words. ' +
        'You can also ask plain questions, such as your re-enrolment date or what your documents say.\n' +
        'Fork uses your payroll export, your pension scheme settings and the documents you’ve confirmed. ' +
        'It never shows you what any employee asked or decided; you see topics only once five or more people have asked.',
  routeTo: null,
  canHelpWith: titles,
});

export const BLOCKED: ForkMessage = {
  kind: 'message',
  reason: 'blocked',
  title: 'Fork couldn’t check this answer',
  body: 'Fork worked this out but couldn’t confirm every part of it, so it won’t show you something that might be wrong. Try asking again, or ask your employer or accountant.',
  routeTo: 'accountant',
};

export const blocked = (checks: NonNullable<ForkMessage['checks']>): ForkMessage => ({ ...BLOCKED, checks });

export const clarify = (description: string): ForkMessage => ({
  kind: 'message',
  reason: 'clarify',
  title: 'Did you mean this?',
  body: `Fork thinks you’re asking about: ${description}. Ask again with a little more detail and Fork will build the screen.`,
  routeTo: null,
});

export const needsFacts = (labels: string[]): ForkMessage => ({
  kind: 'message',
  reason: 'needs_facts',
  title: 'Fork needs a little more information',
  body: `To answer this, Fork needs: ${labels.join('; ')}. Your employer can add these, or you can upload a payslip.`,
  routeTo: 'owner',
});

export const failed = (userMessage: string): ForkMessage => ({ kind: 'message', reason: 'failed', title: 'Something went wrong', body: userMessage, routeTo: null });
