/**
 * Fixed replies for questions that should not get a decision screen. Written by people and
 * reviewed like any other guidance wording; never generated by a model.
 */

export type MessageReason = 'lookup' | 'not_supported' | 'human' | 'distress' | 'clarify' | 'needs_facts' | 'blocked' | 'failed';

export interface ForkMessage {
  kind: 'message';
  reason: MessageReason;
  title: string;
  body: string;
  /** Who can help next. */
  routeTo: 'documents' | 'owner' | 'accountant' | 'support' | null;
  /** Where a looked-up answer came from, such as "Staff handbook, page 4". */
  source?: string;
  /** For "not yet": the decisions Fork can help with today. */
  canHelpWith?: string[];
}

export const DISTRESS: ForkMessage = {
  kind: 'message',
  reason: 'distress',
  title: 'That sounds really hard',
  body:
    'You don’t have to work this out alone. MoneyHelper gives free, impartial help with money worries, paid for by the government: moneyhelper.org.uk. ' +
    'If things feel like too much, Samaritans are there any time on 116 123. ' +
    'If it would help to talk about your pay or pension at work, you can ask your employer privately. Fork won’t tell them you asked.',
  routeTo: 'support',
};

/** An honest "not yet", with what Fork can help with today for this person. */
export const notYet = (titles: string[]): ForkMessage => ({ ...NOT_SUPPORTED, canHelpWith: titles });

export const NOT_SUPPORTED: ForkMessage = {
  kind: 'message',
  reason: 'not_supported',
  title: 'Fork can’t answer that one yet',
  body: 'This is a real decision, but Fork doesn’t have the rules and numbers to work it out reliably yet. Your accountant or employer can help in the meantime.',
  routeTo: 'accountant',
};

export const HUMAN: ForkMessage = {
  kind: 'message',
  reason: 'human',
  title: 'This one needs a person',
  body: 'Fork gives guidance on pay, pensions and benefits at work. For this question, talk to your employer, your accountant or a regulated adviser.',
  routeTo: 'owner',
};

export const LOOKUP_UNKNOWN: ForkMessage = {
  kind: 'message',
  reason: 'lookup',
  title: 'That’s not a decision, so no screen needed',
  body: 'Fork couldn’t find that in your documents yet. Your employer or accountant will know where it is.',
  routeTo: 'owner',
};

export const BLOCKED: ForkMessage = {
  kind: 'message',
  reason: 'blocked',
  title: 'Fork couldn’t check this answer',
  body: 'Fork worked this out but couldn’t confirm every part of it, so it won’t show you something that might be wrong. Try asking again, or ask your employer or accountant.',
  routeTo: 'accountant',
};

export const clarify = (description: string): ForkMessage => ({
  kind: 'message',
  reason: 'clarify',
  title: 'Did you mean this?',
  body: `Fork thinks you’re asking about: ${description}. Ask again with a little more detail and Fork will build the screen.`,
  routeTo: null,
});

export const needsFacts = (labels: string[]): ForkMessage => ({
  kind: 'message',
  reason: 'needs_facts',
  title: 'Fork needs a little more information',
  body: `To answer this, Fork needs: ${labels.join('; ')}. Your employer can add these, or you can upload a payslip.`,
  routeTo: 'owner',
});

export const failed = (userMessage: string): ForkMessage => ({ kind: 'message', reason: 'failed', title: 'Something went wrong', body: userMessage, routeTo: null });
